### ISSUE TITLE
The purity question

### ISSUE THREAD

**Issue by akru** [BumblebeeBat/chalang#2]
The new language for smart contracts is functional, tail recursion optimized, like a lisp, sounds **pretty** good!

But what you can say about purity and strong type inference like a haskell?

**Comment by zack-bitcoin** [comment]
"purity" and "strong types inference" are not things that you solve at the VM level.
Instead they are built into the compiler.
I used the compiler to make lisp macros, and I used that macro system to write a lisp. This lisp has functional purity.
We could add types to this compiler, or write another compiler that does type checks.
Then once we have a type system compiler, we can add type inference like haskell to the compiler.

The blockchain only depends on the VM. The compilers can be written after the blockchain is already running.

**Comment by akru** [comment]
Of course VM don't provide abstractions like a purity and type system,
but this is language repo, right?

So, because you touch virtual machine in this issue, I have some another questions:
- I see [codes](https://github.com/BumblebeeBat/chalang/blob/master/docs/opcodes.md) and it has a lot of language specific primitives and some library like calls (`reverse`, `split`, etc.). Would you planning to separate VM and compiler?
- Would you have VM specs beside `docs`?

**Comment by zack-bitcoin** [comment]
reverse and split are opcodes as much as any of the other opcodes.
All the docs so far are in the docs folder.

There is also examples of forth code in the /src/forth folder.
The forth code is assembly for this VM. Every word is replaced with an opcode.
It also has macros, so it isn't exactly assembly, but very close.

**Comment by akru** [comment]
Summarize the experience of this issue:
- Forth is assembly of VM with hardcoded list operations and something else;
- VM has only three types: 32bit integers, lists and binaries (Erlang list and binaries as I see);
- VM has "real world door" the `print` opcode;
- "reverse and split are opcodes as much as any of the other opcodes" - hmm, why `sort` or `map` isn't opcodes?

**Comment by zack-bitcoin** [comment]
Yes, it seems like you understand the VM pretty well.

sort and map could have been opcodes. Maybe I should add them.

If I didn't make an opcode for split, then there would have been many things that would be impossible to do.

**Comment by akru** [comment]
I will not agree with last statement,
to work with list the `car`, `cons` and `nil` (and patter matching, `compare` or `length` at the worst) all you need is.
If we assume that binary is a list of bytes then binary operations will pass.
IMHO but other list operations is optimizations only.

**Comment by zack-bitcoin** [comment]
you can see the definition of the split opcode here:
https://github.com/BumblebeeBat/chalang/blob/master/src/chalang.erl#L484
It works on binaries and lists.
Binaries are not lists.
You are correct that you can implement split for lists using car cons nil and functions, but you can't use car on binaries.

**Comment by akru** [comment]
So, I see you have type-dependent implementation of `split` why `car`, `cons` and `nil` can't be same?

**Comment by zack-bitcoin** [comment]
lists in erlang are linked lists. So car and cons are the efficient way to use them.
Binaries are stored in contiguous memory. If you append 2 binaries, a contiguous space of memory needs to be allocated to store the larger resultant binary.
The efficient way to modify a binary is with split and append.

It was incorrect of me to allow using split on lists. This could have been a DDOS attack vector. Thank you for bringing it up.

**Comment by akru** [comment]
Keep in mind that in the future you may have more than one implementation of VM. Minimize your Erlang projection to VM lang and opcodes.

Thank your for this observation!

**Comment by zack-bitcoin** [comment]
Yes, I reimplemented a lot of it in rust https://github.com/zack-bitcoin/forth-in-rust
The erlang version is too slow. Building a VM inside of the erlang BEAM VM is a slow strategy.
